repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-yaml

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
      args:
      - --line-length=79
      exclude: run.py


- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      exclude: __init__.py


- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      exclude: __init__.py



- repo: local
  hooks:
    - id: export-dev-requirements
      name: Export DEVELOPMENT requirements
      language: system
      pass_filenames: false
      entry: poetry export --dev --without-hashes --output ./requirements_dev.txt
      files: ^(pyproject.toml|poetry.lock)$

    - id: export-prod-requirements
      name: Export PRODUCTION requirements
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --without dev --output ./requirements.txt
      files: ^(pyproject.toml|poetry.lock)$
